services:

###############
# NGINX
###############
  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    env_file:
      - .env
    volumes:
      - ${NGINX_PROXY_MANAGER_VOLUME}/data:/data
      - ${NGINX_PROXY_MANAGER_VOLUME}/letsencrypt:/etc/letsencrypt
    networks:
      - zimablade

###############
# FILEBROWSER
###############
  filebrowser:
    image: filebrowser/filebrowser:v2-s6
    container_name: filebrowser
    volumes:
      - ${FILEBROWSER_VOLUME}:/srv
    env_file:
      - .env
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500m
    networks:
      - zimablade

###############
# PLEX
###############
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    env_file:
      - .env
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
      - PLEX_CLAIM= #https://account.plex.tv/en-GB/claim
    volumes:
      - ${PLEX_VOLUME}/config:/config
      - ${PLEX_VOLUME}/media:/media
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - zimablade

###############
# QBITTORRENT
###############
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:5.0.3
    container_name: qbittorrent
    env_file:
      - .env
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8096
      - TORRENTING_PORT=6881
    volumes:
      - ${QBITTORRENT_VOLUME}/config:/config
      - ${PLEX_VOLUME}/media:/downloads
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500m
    networks:
      - zimablade
    # network_mode: "service:gluetun"

networks:
  zimablade:
    driver: bridge