services:
###############
# FILEBROWSER
###############
  filebrowser:
    image: filebrowser/filebrowser:v2-s6
    container_name: filebrowser
    volumes:
      - ${FILEBROWSER_VOLUME}:/srv
    env_file:
      - .env
    ports:
      - 1900:80
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500m

###############
# PLEX
###############
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    env_file:
      - .env
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
    volumes:
      - ${PLEX_VOLUME}/config:/config
      - ${PLEX_VOLUME}/media:/media
    ports:
      - 32400:32400
      - 1900:1900/udp
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G

###############
# QBITTORRENT
###############
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:4.6.6
    container_name: qbittorrent
    env_file:
      - .env
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8096
      - TORRENTING_PORT=6881
    volumes:
      - ${QBITTORRENT_VOLUME}/config:/config
      - ${PLEX_VOLUME}/media:/downloads
    ports:
      - 8096:8096
      - 6881:6881
      - 6881:6881/udp
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500m